import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Taypro',
      email: 'admin@taypro.in',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Vaibhav',
      email: 'user@taypro.in',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  tickets: [
    {
      ticketId: '1',
      siteName: 'AVHADA',
      plotNo: '09',
      blockNo: '12',
      robotId: '1234AVHADA',
      fault: 'Cupling',
      detailedIssue: 'xyz',
      problemSolved: 'NO',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '12/03/2023',
      closedDate: '15/03/2023',
    },
    {
      ticketId: '2',
      siteName: 'ADANI',
      plotNo: '02',
      blockNo: '12',
      robotId: '1234ADANI',
      fault: 'Brushes',
      detailedIssue: 'xyz',
      problemSolved: 'NO',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '13/03/2023',
      closedDate: '17/03/2023',
    },
    {
      ticketId: '3',
      siteName: 'AMPLUS',
      plotNo: '06',
      blockNo: '12',
      robotId: '1234AMPLUS',
      fault: 'Gear',
      detailedIssue: 'abc',
      problemSolved: 'YES',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '11/03/2023',
      closedDate: '12/03/2023',
    },
    {
      ticketId: '4',
      siteName: 'AVHADA',
      plotNo: '09',
      blockNo: '12',
      robotId: '1234AVHADA',
      fault: 'Cupling',
      detailedIssue: 'xyz',
      problemSolved: 'NO',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '12/03/2023',
      closedDate: '15/03/2023',
    },
    {
      ticketId: '5',
      siteName: 'ADANI',
      plotNo: '02',
      blockNo: '12',
      robotId: '1234ADANI',
      fault: 'Brushes',
      detailedIssue: 'xyz',
      problemSolved: 'NO',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '13/03/2023',
      closedDate: '17/03/2023',
    },
    {
      ticketId: '6',
      siteName: 'AMPLUS',
      plotNo: '06',
      blockNo: '12',
      robotId: '1234AMPLUS',
      fault: 'Gear',
      detailedIssue: 'abc',
      problemSolved: 'YES',
      partsChanged: 'brushes',
      image: '/images/taypro1.jpg',
      status: 'Pending',
      openDate: '11/03/2023',
      closedDate: '12/03/2023',
    },
  ],
};

export default data;
